To update your workflow and fix the deprecated `actions/upload-artifact: v2`, you will need to change the following:

1. Update the `actions/upload-artifact@v2` to `actions/upload-artifact@v3`.
2. Also, you can update other actions to their latest versions, such as `actions/checkout@v3` and `actions/setup-python@v4`.

Here’s your modified workflow:

```yaml
name: Image Workflow

on:
  push:
    paths:
      - 'icon/**' # 监视 icons 文件夹及其子文件夹下的内容
  pull_request:
    paths:
      - 'icon/**' # 监视 icons 文件夹及其子文件夹下的内容
  workflow_dispatch:

jobs:
  generate_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate JSON
      run: |
        python .github/scripts/generate_image_json.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: json-artifact
        path: ${{ github.workspace }}/mikephie.icons.json

    - name: Push to QuantumultX Repository
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "自动更新图标仓库"
        git push origin HEAD:main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Changes made:
- Updated `actions/checkout@v2` to `actions/checkout@v3`.
- Updated `actions/setup-python@v2` to `actions/setup-python@v4`.
- Updated `actions/upload-artifact@v2` to `actions/upload-artifact@v3`.

This should resolve the deprecation issue and ensure your workflow is using the latest versions. Let me know if you need further adjustments!
